DROP TABLE IF EXISTS shops;

CREATE TABLE shops (
  id int(6) NOT NULL AUTO_INCREMENT,
  name varchar(60) NOT NULL,
  employees_number int(6) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE role (
  id int(6) NOT NULL AUTO_INCREMENT,
  name varchar(60) NOT NULL,
  UNIQUE (name),
  PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
